includes = ["src/satori/adapters/onebot11"]
raw-dependencies = ["satori-python-server >= 0.16.4"]

[project]
name = "satori-python-adapter-onebot11"
version = "0.1.1"
authors = [
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = []
description = "Satori Protocol SDK for python, adapter for OneBot 11"
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

[project.urls]
homepage = "https://github.com/RF-Tar-Railt/satori-python"
repository = "https://github.com/RF-Tar-Railt/satori-python"
